---
title: "Milestone 1"
author: "Group 8: Erin Curlee, Val Stacey, Ana Terzo"
date: "09/30/2025"
format: 
  html:
    self-contained: true
execute:
  message: false
  warning: false
---


# Project option selection: 

**Scenario 1: Infectious disease outbreak (simulated) in California**


**Group 8 git repository link:** <https://github.com/EvalstacE/Group08_PHW251_R> 

\newpage

------------------------------------------------

# Roles and Responsibilities

### Communication method: 

Group text messages and email if needed

### Meeting times and frequency: 

When will your team be holding meetings? How frequently will you meet? 
Are there times or days that work well for everyone?

+ We have a scheudled standing meeting every Thursday at 5PM PST, not to go past 7PM

+ if the meeting is not needed - we will text each other and can cancel




**Curlee**: 

  + Timezone: PST
  
  + Available days: every other Friday during the day; after 2 PM Sat/Sun
  
  + Available times: after 5 PM 
  
  + Any upcoming commitments affecting availability: November 14th birthday - taking some time off around then
  

**Val**: 

  + Timezone: Mountain
  
  + Available days: all
  
  + Available times: weekends: anytime; weekdays: anytime after 5PM MST
  

**Ana**: 

  + Timezone: PST
  
  + Available days: tuesdays/thursdays/fridays best
  
  + Available times: after work 
  

------------------------------------------------


\newpage


### Method for tracking progress: 

How is your team going to keep track of progress? 

+ We have our github repo organized with milestone folders to help keep us on track

+ We will assign roles and tasks as needed at our weekly check-in meetings for upcoming assignments



For contacting the course facilitators with questions:

+ Point person: Val

+ Erin and Ana as secondary


------------------------------------------------


\newpage


## Conflict Management


If a conflict arises, plan to solve the issue as soon as possible. 

This is best done using synchronous (Zoom, Google Hangouts) communication rather than asynchronous (email).

If the group is unable to resolve the conflict, seek advice from the instructional team. 



