# R Packages {.unnumbered}


## Data Wrangling {.unnumbered}

## `readr`
Reads text data (CSV, TSV) efficiently into R data frames (tibbles).

  Wickham H, Hester J, Bryan J (2024). _readr: Read Rectangular Text
  Data_. R package version 2.1.5
  <https://CRAN.R-project.org/package=readr>.
  
### `here` 
Simplifies file paths by automatically locating the project root

  Müller K (2020). _here: A Simpler Way to Find Your Files_. R package
  version 1.0.1
  <https://CRAN.R-project.org/package=here>.
  

### `dplyr` 
Core data manipulation package for filtering, selecting, summarizing, and transforming data frames.

  Wickham H, François R, Henry L, Müller K, Vaughan D (2023). _dplyr: A Grammar
  of Data Manipulation_. R package version 1.1.4
  <https://CRAN.R-project.org/package=dplyr>.


### `tidyr` 
Reshapes data between wide and long formats.

  Wickham H, Vaughan D, Girlich M (2024). _tidyr: Tidy Messy Data_. R package
  version 1.3.1
  <https://CRAN.R-project.org/package=tidyr>.


### `janitor`
Cleans variable names and performs quick data cleaning tasks

  Firke S (2023). _janitor: Simple Tools for Examining and Cleaning
  Dirty Data_. R package version 2.2.0
  <https://CRAN.R-project.org/package=janitor>.


### `lubridate`
Simplifies parsing, manipulating, and calculating with dates and times.

  Garrett Grolemund, Hadley Wickham (2011). Dates and Times Made Easy
  with lubridate. Journal of Statistical Software, 40(3), 1-25
  <https://www.jstatsoft.org/v40/i03/>.


### `stringr` 
Consistent, easy-to-use functions for working with strings and regular expressions.

  Wickham H (2023). _stringr: Simple, Consistent Wrappers for Common
  String Operations_. R package version 1.5.1
  <https://CRAN.R-project.org/package=stringr>.
  
  
### `scales`
Provides tools for controlling how data values are mapped to aesthetics (like adding a thousandth comma separator, e.g: '1,000` instead of 1000)

  Wickham H, Pedersen T, Seidel D (2023). _scales: Scale Functions for
  Visualization_. R package version 1.3.0,
  <https://CRAN.R-project.org/package=scales>.
  

### `purrr` 
Functional programming tools for working with lists, iteration, and mapping operations.

  Wickham H, Henry L (2025). _purrr: Functional Programming Tools_. R
  package version 1.0.4
  <https://CRAN.R-project.org/package=purrr>.
  

### `rlang`
Provides tools for tidy evaluation and programming with tidyverse-style functions.

  Henry L, Wickham H (2025). _rlang: Functions for Base Types and Core R
  and 'Tidyverse' Features_. R package version 1.1.5
  <https://CRAN.R-project.org/package=rlang>.
  
  
### `MMWRweek`
Converts calendar dates to MMWR (epidemiological) weeks and years for public health analyses.

  Niemi J (2020). _MMWRweek: Convert Dates to MMWR Day, Week, and
  Year_. R package version 0.1.3
  <https://CRAN.R-project.org/package=MMWRweek>.


## Data Visualization {.unnumbered}


### `knitr`
Powers dynamic report generation by embedding R code and output into documents.

  Xie Y (2025). _knitr: A General-Purpose Package for Dynamic Report
  Generation in R_. R package version 1.50
  <https://yihui.org/knitr/>.

  Yihui Xie (2015) Dynamic Documents with R and knitr. 2nd edition.
  Chapman and Hall/CRC. ISBN 978-1498716963

  Yihui Xie (2014) knitr: A Comprehensive Tool for Reproducible Research
  in R. In Victoria Stodden, Friedrich Leisch and Roger D. Peng,
  editors, Implementing Reproducible Computational Research. Chapman and
  Hall/CRC. ISBN 978-1466561595
  
  
### `kableExtra`
Extends knitr tables with advanced formatting and styling for HTML and LaTeX.  

  Zhu H (2024). _kableExtra: Construct Complex Table with 'kable' and
  Pipe Syntax_. R package version 1.4.0
  <https://CRAN.R-project.org/package=kableExtra>.  
  
  

### `ggplot2` 
Creates customizable, publication-quality data visualizations.

  H. Wickham. ggplot2: Elegant Graphics for Data Analysis.
  Springer-Verlag New York, 2016.
  <https://ggplot2.tidyverse.org>

