# Course of the Outbreak

```{r, echo = FALSE}

source("ca_mnth_tbl_code.R")


```




## Statewide Infections by Month
##### *May 2023 - Dec 2023*


```{r, echo = FALSE}

ca_mnth_tbl

```





|
|
|


## Timeline of the Outbreak

### *May 2023 - December 2023*

--------------

::: {.indent-block}
##### *May 28, 2023:*

California had reported 13,875 infections. Infections increased rapidly throughout June and early July, with weekly new cases rising **50 to 100 percent** compared with the previous week, the most instense growth phase of the outbreak this year.


##### *Late July - September:*

The outbreak began to slow. Weekly increases in new cases dropped to **20 to 30 percent.**


##### *October:*

Growth had slowed even further, with weekly increases approaching single digits.

##### *Mid-November:* 

Growth in weekly percent change in new case slowed to less than 1%


##### *As of December 30:* 

Although overall infections have continued to decline, we are still getting reports of new cases. 

Most importantly is that there is now a much **higher proportion of new infections that are severe and require hospitalization.**

While the State of California is seeing dramatically fewer infections overall, seeing a higher proportion of infections that are severe requires our continued vigilance and dedication to address this outbreak as a community: maintaining clinical capacity, strengthening rapid detection, and ensuring that the communities being hit the hardest get the resources they need. 

:::


------------

::: {.wide-embed}

```{=html}

<iframe 
  src="https://evalue.shinyapps.io/Group08_County_Weekly_Map/"
  width="100%" 
  height="1000px" 
  frameborder="0">
</iframe>

```

:::




|
|
|





#### Supporting Code: 

The full code for the weekly case map can be found on the github repository within the "cases_week_app" branch:
**<https://github.com/EvalstacE/Group08_PHW251_R/tree/cases_week_app>**

[Download Shiny App Code (ZIP)](../../www/Group08_weekly_case_map_shiny_app.zip){.btn .btn-primary target="_blank"}

|

[Download Full Table Code (ZIP)](../../www/ca_mnth_tbl_code.zip){.btn .btn-primary target="_blank"}

|

[Download Weekly Infection Rates (CSV)](../../data/inf_rate_dfs/ca_weekly_cases.csv){.btn .btn-primary target="_blank"}

|


**Creating and saving shapefiles for maps:**

```{r, eval = FALSE}

##--bring in California shapefile and 
###---join to infection rate dataframe
ca_cnty_sf <- counties(state = "CA", cb = TRUE, year = 2023) %>%
  st_as_sf() %>%
  select(NAME) %>%
  rename("county" = "NAME") %>%
  st_transform(4326)

##--state border only
ca_state_sf <- states(cb = TRUE, year = 2023) %>%
  st_as_sf() %>%
  filter(STUSPS == "CA") %>%
  select(STATEFP, STUSPS, GEOIDFQ, GEOID) %>%
  st_transform(4326)


##--dissolves counties into Health Officer Regions
hor_sf <- ca_cnty_sf %>%
  group_by(health_officer_region) %>%
  summarise(.groups = "drop")%>%
  st_cast("MULTIPOLYGON")%>%
  st_transform(4326)



##--save to data/shapefiles folder
##-st_write(ca_cnty_sf, here("data/shapefiles/ca_cnty_sf/ca_cnty_sf.shp"), append = FALSE)
##-st_write(hor_sf, here("data/shapefiles/hor_sf/hor_sf.shp"), append = FALSE)
##-st_write(ca_state_sf, here("data/shapefiles/ca_state_sf/ca_state_sf.shp"), append = FALSE)


```


